name:                fp-compiler
version:             0.1.0.0
github:              "dat2/fp-compiler"
license:             BSD3
author:              "Nick Dujay"
maintainer:          "nickdujay@gmail.com"
copyright:           "Nick Dujay 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dat2/fp-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- llvm-hs
- llvm-hs-pure
- llvm-hs-pretty
- megaparsec
- mtl
- recursion-schemes
- text

library:
  source-dirs: src

executables:
  fp-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-compiler

tests:
  fp-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-compiler
